#!/usr/bin/env python3
"""AIL function opcode tables ported from AIL_Tools Script.cs.

Each sub opcode maps to a tuple of field actions:
  expr: consume one AIL expression
  text: consume one u16 string-pool offset and record it
"""

FUNC_TABLES = {0: {0: ('text',),
     1: ('text',),
     2: ('expr',),
     3: (),
     4: (),
     5: (),
     6: (),
     7: (),
     8: ('expr', 'expr', 'expr', 'expr', 'text'),
     9: ('expr', 'expr', 'expr', 'expr', 'text'),
     10: (),
     11: (),
     12: ('expr',),
     16: ('expr',),
     17: (),
     18: ('expr',),
     19: (),
     20: (),
     21: ('expr',),
     22: ('expr', 'expr'),
     23: ('expr',),
     24: ('expr',),
     25: ('expr', 'expr', 'expr'),
     26: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     27: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     28: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     29: ('expr', 'expr', 'expr', 'expr', 'expr'),
     30: ('expr', 'expr', 'expr'),
     31: ('expr', 'expr'),
     32: ('expr', 'expr', 'expr', 'expr'),
     33: ('expr', 'expr', 'expr', 'expr'),
     34: ('expr', 'expr', 'expr'),
     35: ('expr', 'expr', 'expr', 'expr', 'expr'),
     36: ('expr', 'expr', 'expr', 'expr', 'expr'),
     37: ('expr', 'expr', 'expr', 'expr'),
     38: ('expr', 'expr', 'expr', 'expr'),
     39: ('expr', 'expr', 'expr', 'expr', 'expr'),
     40: ('expr', 'expr'),
     41: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     42: ('expr', 'expr'),
     43: ('expr',),
     44: ('expr',),
     45: ('expr',),
     46: ('expr',),
     47: (),
     48: ('expr', 'expr'),
     49: ('expr', 'expr'),
     50: ('expr',),
     51: ('expr',),
     52: ('expr',),
     53: ('expr',),
     54: ('expr',),
     55: ('expr',),
     56: ('expr', 'expr'),
     57: ('expr', 'expr'),
     58: ('expr', 'expr'),
     59: ('expr', 'expr'),
     60: ('expr',),
     61: ('expr',),
     62: ('expr',),
     63: ('expr',),
     64: ('expr', 'expr'),
     65: ('expr',),
     66: (),
     67: (),
     68: ('expr', 'expr'),
     69: ('expr',),
     70: ('expr', 'expr', 'expr'),
     71: ('expr',),
     72: ('expr', 'expr'),
     73: ('expr', 'expr'),
     74: (),
     75: (),
     76: ('expr',),
     77: ('expr',),
     78: ('expr',),
     79: ('expr',),
     80: ('expr', 'expr'),
     81: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     82: ('expr', 'expr', 'expr'),
     83: ('expr', 'expr', 'expr'),
     84: (),
     85: ('expr',),
     86: ('expr', 'expr'),
     87: ('expr',),
     88: ('expr',),
     89: (),
     90: ('expr',),
     91: ('expr',),
     92: (),
     93: ('expr',),
     94: ('expr',),
     95: ('expr', 'expr'),
     96: ('expr', 'expr'),
     97: ('expr',),
     98: ('expr',),
     99: ('expr', 'expr'),
     100: ('expr', 'expr'),
     101: ('expr', 'expr'),
     102: ('expr', 'expr'),
     103: ('expr', 'expr', 'expr'),
     104: ('expr', 'expr', 'expr'),
     105: ('expr',),
     106: ('expr',),
     107: ('expr', 'expr', 'expr', 'expr'),
     108: ('expr', 'expr', 'expr', 'expr', 'text'),
     109: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     110: ('text', 'expr'),
     111: ('expr', 'expr', 'expr', 'expr', 'expr'),
     112: ('expr',),
     113: ('expr',),
     114: ('expr',),
     115: ('expr', 'expr'),
     116: ('expr', 'expr', 'expr', 'expr'),
     117: (),
     118: (),
     119: ('expr',),
     120: ('expr',),
     121: ('expr',),
     122: ('expr', 'expr'),
     123: (),
     124: (),
     126: ('expr', 'expr', 'expr', 'expr', 'text'),
     127: ('expr',),
     128: ('expr', 'expr'),
     129: ('expr', 'expr', 'expr', 'expr'),
     130: ('expr',),
     131: ('expr', 'text'),
     132: ('expr',),
     133: ('expr',),
     134: ('expr',),
     135: ('expr', 'expr', 'expr'),
     136: ('expr', 'expr', 'expr'),
     137: ('expr', 'expr'),
     138: ('text',),
     139: ('expr',),
     140: ('expr',),
     141: ('expr',),
     142: ('expr',),
     143: ('expr', 'expr'),
     144: ('expr', 'expr', 'expr', 'expr', 'expr'),
     145: ('expr', 'expr'),
     146: (),
     147: (),
     148: ('expr', 'text'),
     149: ('expr', 'expr'),
     150: ('expr',),
     151: ('expr', 'expr'),
     152: ('expr', 'expr'),
     153: ('expr', 'expr', 'expr'),
     154: ('expr',),
     155: ('expr', 'expr', 'expr', 'expr'),
     156: ('expr', 'expr', 'expr', 'expr', 'expr'),
     157: ('expr', 'expr', 'expr', 'expr', 'text'),
     158: ('expr',),
     159: ('expr', 'expr', 'expr'),
     160: ('expr', 'expr', 'expr', 'expr', 'expr', 'text'),
     161: ('expr', 'expr'),
     162: ('expr',),
     163: (),
     164: ('expr', 'expr', 'expr', 'expr', 'expr'),
     165: ('expr', 'expr', 'expr', 'expr'),
     166: (),
     167: (),
     168: (),
     169: ('expr',),
     170: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     171: (),
     172: ('expr', 'expr', 'expr', 'expr'),
     173: ('expr',),
     174: ('expr', 'expr', 'expr', 'expr', 'expr'),
     175: (),
     176: ('expr',),
     177: (),
     178: ('expr',),
     179: (),
     180: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     181: ('expr', 'expr', 'expr', 'expr'),
     182: (),
     183: ('expr', 'expr', 'expr', 'expr', 'text'),
     184: ('expr', 'expr', 'expr', 'expr', 'text'),
     185: ('expr',),
     186: (),
     187: ('expr',),
     188: ('expr',),
     189: ('expr',),
     190: ('expr',),
     191: ('expr', 'expr', 'expr'),
     192: ('expr', 'expr', 'expr', 'expr'),
     193: ('expr', 'expr', 'expr', 'expr'),
     194: (),
     195: ('expr', 'expr'),
     196: ('expr', 'expr'),
     197: ('expr', 'expr'),
     198: ('expr', 'expr'),
     199: ('expr', 'expr', 'expr', 'expr'),
     200: ('expr', 'expr'),
     201: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     202: (),
     203: (),
     204: (),
     205: (),
     206: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     207: (),
     208: ('expr', 'expr'),
     209: ('expr', 'expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     210: ('expr',),
     211: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr'),
     212: ('expr', 'expr'),
     213: ('expr', 'expr'),
     214: ('expr',),
     215: ('text',),
     216: (),
     217: (),
     218: (),
     219: (),
     220: (),
     221: ('expr', 'expr', 'expr'),
     222: ('expr', 'expr', 'expr', 'expr', 'expr'),
     223: ('expr', 'expr', 'expr', 'expr', 'expr'),
     224: ('expr', 'expr', 'expr', 'expr', 'expr'),
     225: ('expr',),
     226: (),
     227: ('expr',),
     228: ('expr',),
     229: ('expr', 'expr', 'expr', 'expr'),
     230: (),
     231: ('expr', 'expr', 'expr', 'expr', 'expr'),
     232: ('expr', 'expr', 'expr', 'expr', 'expr'),
     233: (),
     234: (),
     235: ('expr', 'expr'),
     236: ('text', 'expr'),
     237: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     238: ('expr',),
     239: ('expr', 'expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     240: ('expr',),
     241: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     242: ('expr',),
     243: ('expr',),
     244: ('expr', 'expr'),
     245: ('expr', 'expr', 'expr'),
     246: ('expr',),
     247: ('expr',),
     248: ('expr',),
     249: ('expr',),
     250: ('expr',),
     251: ('expr',),
     252: ('expr',)},
 1: {0: ('text',),
     1: ('text',),
     2: ('expr',),
     3: (),
     4: (),
     5: (),
     6: (),
     7: (),
     8: ('expr', 'expr', 'expr', 'expr', 'text'),
     9: ('expr', 'expr', 'expr', 'expr', 'text'),
     10: ('expr', 'expr'),
     11: (),
     12: ('expr',),
     16: ('expr',),
     17: (),
     18: ('expr',),
     19: (),
     21: ('expr',),
     22: ('expr', 'expr'),
     24: ('expr',),
     25: ('expr', 'expr', 'expr'),
     26: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     27: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     28: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     29: ('expr', 'expr', 'expr', 'expr', 'expr'),
     30: ('expr', 'expr', 'expr'),
     31: ('expr', 'expr'),
     32: ('expr', 'expr', 'expr', 'expr'),
     33: ('expr', 'expr', 'expr', 'expr'),
     34: ('expr', 'expr', 'expr'),
     35: ('expr', 'expr', 'expr', 'expr', 'expr'),
     37: ('expr', 'expr', 'expr', 'expr'),
     38: ('expr', 'expr', 'expr', 'expr'),
     39: ('expr', 'expr', 'expr', 'expr', 'expr'),
     40: ('expr', 'expr'),
     41: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     42: ('expr', 'expr'),
     43: ('expr',),
     44: ('expr',),
     45: ('expr',),
     46: ('expr',),
     47: (),
     48: ('expr', 'expr'),
     49: ('expr', 'expr'),
     50: ('expr',),
     52: ('expr',),
     53: ('expr',),
     55: ('expr',),
     56: ('expr', 'expr'),
     59: ('expr',),
     63: ('expr',),
     64: ('expr', 'expr'),
     65: ('expr',),
     66: (),
     67: (),
     68: ('expr', 'expr'),
     69: ('expr',),
     70: ('expr', 'expr', 'expr'),
     71: ('expr',),
     72: ('expr', 'expr'),
     74: (),
     75: (),
     76: ('expr',),
     77: ('expr',),
     81: ('expr',),
     86: ('expr', 'expr'),
     87: ('expr',),
     88: ('expr',),
     89: (),
     90: ('expr',),
     91: ('expr',),
     93: ('expr',),
     94: ('expr',),
     95: ('expr', 'expr'),
     96: ('expr', 'expr'),
     97: ('expr',),
     98: ('expr',),
     99: ('expr', 'expr'),
     100: ('expr', 'expr'),
     101: ('expr', 'expr'),
     102: ('expr', 'expr'),
     103: ('expr', 'expr', 'expr'),
     104: ('expr', 'expr', 'expr'),
     105: ('expr',),
     108: ('expr', 'expr', 'expr', 'expr', 'text'),
     109: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     110: ('text', 'expr'),
     111: ('expr', 'expr', 'expr', 'expr', 'expr'),
     112: ('expr',),
     118: (),
     120: ('expr',),
     122: ('expr', 'expr'),
     126: ('expr', 'expr', 'expr', 'expr', 'text'),
     127: ('expr',),
     129: ('expr', 'expr', 'expr', 'expr'),
     130: ('expr',),
     131: ('expr', 'text'),
     132: ('expr',),
     133: ('expr',),
     134: ('expr',),
     135: ('expr', 'expr', 'expr'),
     136: ('expr', 'expr', 'expr'),
     137: ('expr', 'expr'),
     138: ('text',),
     139: ('expr',),
     140: ('expr',),
     141: ('expr',),
     142: ('expr',),
     143: ('expr', 'expr'),
     144: ('expr', 'expr', 'expr', 'expr', 'expr'),
     145: ('expr', 'expr'),
     146: (),
     147: (),
     148: ('expr', 'text'),
     149: ('expr', 'expr'),
     150: ('expr',),
     151: ('expr', 'expr'),
     152: ('expr', 'expr'),
     153: ('expr', 'expr', 'expr'),
     154: ('expr',),
     155: ('expr', 'expr', 'expr', 'expr'),
     156: ('expr', 'expr', 'expr', 'expr', 'expr'),
     157: ('expr', 'expr', 'expr', 'expr', 'text'),
     158: ('expr',),
     160: ('expr', 'expr', 'expr', 'expr', 'expr', 'text'),
     161: ('expr', 'expr'),
     164: ('expr', 'expr', 'expr', 'expr', 'expr'),
     165: ('expr', 'expr', 'expr', 'expr'),
     166: (),
     168: (),
     169: ('expr',),
     170: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     171: (),
     172: ('expr', 'expr', 'expr', 'expr'),
     175: (),
     178: ('expr',),
     179: (),
     180: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     181: ('expr', 'expr', 'expr', 'expr'),
     182: (),
     183: ('expr', 'expr', 'expr', 'expr', 'text'),
     184: ('expr', 'expr', 'expr', 'expr', 'text'),
     185: ('expr',),
     186: (),
     187: ('expr',),
     188: ('expr',),
     189: ('expr',),
     190: ('expr',),
     191: ('expr', 'expr', 'expr'),
     192: ('expr', 'expr', 'expr', 'expr'),
     193: ('expr', 'expr', 'expr', 'expr'),
     194: (),
     195: ('expr', 'expr'),
     196: ('expr', 'expr'),
     197: ('expr', 'expr'),
     198: ('expr', 'expr'),
     199: ('expr', 'expr', 'expr', 'expr'),
     200: ('expr', 'expr'),
     201: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     202: (),
     203: (),
     204: (),
     205: (),
     206: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     207: (),
     208: ('expr', 'expr'),
     209: ('expr', 'expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     210: ('expr',),
     211: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr'),
     212: ('expr', 'expr'),
     213: ('expr', 'expr'),
     214: ('expr',),
     215: ('text',),
     216: (),
     217: (),
     222: ('expr', 'expr', 'expr', 'expr', 'expr'),
     223: ('expr', 'expr', 'expr', 'expr', 'expr'),
     224: ('expr', 'expr', 'expr', 'expr', 'expr'),
     225: ('expr',),
     226: (),
     228: ('expr',),
     229: ('expr', 'expr', 'expr', 'expr'),
     230: (),
     232: ('expr', 'expr', 'expr', 'expr', 'expr'),
     233: (),
     234: (),
     235: ('expr', 'expr'),
     236: ('text', 'expr'),
     237: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     239: ('expr', 'expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     240: ('expr',),
     241: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     243: ('expr',),
     244: ('expr', 'expr'),
     245: ('expr', 'expr', 'expr'),
     248: ('expr',),
     249: ('expr',),
     250: ('expr',),
     251: ('expr',),
     252: ('expr',),
     253: ('expr', 'expr'),
     254: ('expr', 'expr'),
     255: ()},
 2: {0: ('text',),
     1: ('text',),
     2: ('expr',),
     3: (),
     4: (),
     5: (),
     6: (),
     7: (),
     8: ('expr', 'expr', 'expr', 'expr', 'text'),
     9: ('expr', 'expr', 'expr', 'expr', 'text'),
     10: ('expr', 'expr'),
     11: (),
     12: ('expr',),
     13: ('expr', 'expr', 'expr', 'expr'),
     14: ('expr', 'expr', 'expr', 'expr'),
     15: ('expr', 'expr'),
     16: ('expr',),
     17: (),
     18: ('expr',),
     19: (),
     20: (),
     21: ('expr',),
     22: ('expr', 'expr'),
     23: ('expr',),
     24: ('expr',),
     25: ('expr',),
     26: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     27: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     28: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     29: ('expr', 'expr', 'expr', 'expr', 'expr'),
     30: ('expr', 'expr', 'expr'),
     31: ('expr', 'expr'),
     32: ('expr', 'expr', 'expr', 'expr'),
     33: ('expr', 'expr', 'expr', 'expr'),
     34: ('expr', 'expr', 'expr'),
     35: ('expr', 'expr', 'expr', 'expr', 'expr'),
     36: ('expr',),
     37: ('expr', 'expr', 'expr', 'expr'),
     38: ('expr', 'expr', 'expr', 'expr'),
     39: ('expr', 'expr', 'expr', 'expr', 'expr'),
     40: ('expr', 'expr'),
     41: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     42: ('expr', 'expr'),
     43: ('expr',),
     44: ('expr',),
     45: ('expr',),
     46: ('expr',),
     47: (),
     48: ('expr', 'expr'),
     49: ('expr', 'expr'),
     50: ('expr',),
     51: ('expr',),
     52: ('expr',),
     53: ('expr',),
     54: ('expr',),
     55: ('expr',),
     56: ('expr', 'expr'),
     57: ('expr', 'expr'),
     58: ('expr', 'expr'),
     59: ('expr', 'expr'),
     60: ('expr',),
     61: ('expr',),
     62: ('expr',),
     63: ('expr',),
     64: ('expr', 'expr'),
     65: ('expr',),
     66: (),
     67: (),
     68: ('expr', 'expr'),
     69: ('expr',),
     70: ('expr', 'expr', 'expr'),
     71: ('expr',),
     72: ('expr', 'expr'),
     73: ('expr', 'expr'),
     74: (),
     75: (),
     76: ('expr',),
     77: ('expr',),
     78: ('expr',),
     79: ('expr',),
     80: ('expr', 'expr'),
     81: ('expr', 'expr', 'expr', 'expr', 'expr'),
     82: ('text',),
     83: ('expr',),
     84: ('expr', 'expr'),
     85: ('expr',),
     86: ('expr', 'expr'),
     87: ('expr',),
     88: ('expr',),
     89: (),
     90: ('expr',),
     91: ('expr',),
     92: (),
     93: ('expr',),
     94: ('expr',),
     95: ('expr', 'expr'),
     96: ('expr', 'expr'),
     97: ('expr',),
     98: ('expr',),
     99: ('expr', 'expr'),
     100: ('expr', 'expr'),
     101: ('expr', 'expr'),
     102: ('expr', 'expr'),
     103: ('expr', 'expr', 'expr'),
     104: ('expr', 'expr', 'expr'),
     105: ('expr',),
     106: ('expr',),
     107: ('expr', 'expr', 'expr', 'expr'),
     108: ('expr', 'expr', 'expr', 'expr', 'text'),
     109: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     110: ('text', 'expr'),
     111: ('expr', 'expr', 'expr', 'expr', 'expr'),
     112: ('expr',),
     113: ('expr',),
     114: ('expr',),
     115: ('expr', 'expr'),
     116: ('expr', 'expr', 'expr', 'expr'),
     117: (),
     118: (),
     119: ('expr',),
     120: ('expr',),
     121: ('expr', 'expr', 'expr', 'text'),
     122: ('expr', 'expr'),
     123: (),
     124: (),
     125: ('text',),
     126: ('expr', 'expr'),
     127: ('expr',),
     128: ('expr', 'expr'),
     129: ('expr', 'expr', 'expr', 'expr'),
     130: ('expr',),
     131: ('expr', 'text'),
     132: ('expr',),
     133: ('expr',),
     134: ('expr',),
     135: ('expr', 'expr', 'expr'),
     136: ('expr', 'expr', 'expr'),
     137: ('expr', 'expr', 'expr'),
     138: ('text',),
     139: ('expr',),
     140: ('expr',),
     141: ('expr',),
     142: ('expr',),
     143: ('expr', 'expr'),
     144: ('expr', 'expr', 'expr', 'expr', 'expr'),
     145: ('expr', 'expr'),
     146: (),
     147: (),
     148: ('expr', 'text'),
     149: ('expr', 'expr'),
     150: ('expr',),
     151: ('expr', 'expr'),
     152: ('expr', 'expr'),
     153: ('expr', 'expr', 'expr'),
     154: ('expr',),
     155: ('expr', 'expr', 'expr', 'expr'),
     156: ('expr', 'expr', 'expr', 'expr', 'expr'),
     157: ('expr', 'expr', 'expr', 'expr', 'text'),
     158: ('expr',),
     159: ('expr', 'expr', 'expr', 'expr', 'expr', 'text'),
     160: ('expr', 'expr'),
     161: ('expr',),
     162: (),
     163: ('expr', 'expr', 'expr', 'expr', 'expr'),
     164: ('expr', 'expr', 'expr', 'expr'),
     165: (),
     166: ('expr',),
     167: (),
     168: ('expr',),
     169: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     170: (),
     171: ('expr', 'expr', 'expr', 'expr'),
     172: ('expr',),
     173: ('expr', 'expr', 'expr', 'expr', 'expr'),
     174: (),
     175: ('expr',),
     176: (),
     177: ('expr',),
     178: (),
     179: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     180: ('expr', 'expr', 'expr', 'expr'),
     181: (),
     182: ('expr', 'expr', 'expr', 'expr', 'text'),
     183: ('expr', 'expr', 'expr', 'expr', 'text'),
     184: ('expr',),
     185: (),
     186: ('expr',),
     187: ('expr',),
     188: ('expr',),
     189: ('expr',),
     190: ('expr', 'expr', 'expr'),
     191: ('expr', 'expr', 'expr', 'expr'),
     192: ('expr', 'expr', 'expr', 'expr'),
     193: (),
     194: ('expr', 'expr'),
     195: ('expr', 'expr'),
     196: ('expr', 'expr'),
     197: ('expr', 'expr'),
     198: ('expr', 'expr', 'expr', 'expr'),
     199: ('expr', 'expr'),
     200: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     201: (),
     202: (),
     203: (),
     204: (),
     205: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     206: ('text', 'expr'),
     207: ('expr', 'expr'),
     208: ('expr', 'expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     209: ('expr',),
     210: ('expr', 'expr', 'text', 'expr', 'expr', 'expr', 'expr'),
     211: ('expr', 'expr'),
     212: ('expr', 'expr'),
     213: ('expr',),
     214: ('text',),
     215: (),
     216: (),
     217: (),
     218: (),
     219: (),
     220: ('expr', 'expr', 'expr'),
     221: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     222: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     223: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     224: ('expr',),
     225: (),
     226: ('expr', 'expr', 'expr', 'expr', 'expr'),
     227: ('expr',),
     228: ('expr', 'expr', 'expr', 'expr'),
     229: (),
     230: ('expr', 'expr', 'expr', 'expr', 'expr'),
     231: ('expr', 'expr', 'expr', 'expr', 'expr'),
     232: (),
     233: (),
     234: ('expr', 'expr', 'expr'),
     235: ('text', 'expr'),
     236: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     237: ('expr',),
     238: (),
     239: ('expr',),
     240: ('expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr', 'expr'),
     241: ('expr',),
     242: ('expr',),
     243: ('expr', 'expr'),
     244: ('expr', 'expr', 'expr'),
     245: ('expr',),
     246: ('expr',),
     247: ('expr',),
     248: ('expr',),
     249: ('expr',),
     250: ('expr',),
     251: ('expr',),
     252: ('expr', 'expr'),
     253: ('expr', 'expr'),
     254: (),
     255: ('text',)}}

TEXT_SUBOPS = {ver: tuple(sorted(k for k, v in table.items() if "text" in v)) for ver, table in FUNC_TABLES.items()}
